#!/bin/bash

# AWS Security Cleanup Script

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║              🔒 AWS SECURITY CLEANUP                                 ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

echo "⚠️  YOUR AWS CREDENTIALS WERE EXPOSED!"
echo ""
echo "📋 STEPS TO SECURE YOUR ACCOUNT:"
echo ""

echo "1️⃣  ROTATE AWS ACCESS KEYS (DO THIS NOW!)"
echo "   ----------------------------------------"
echo "   a. Go to: https://console.aws.amazon.com/iam/home#/security_credentials"
echo "   b. Find Access Key: AKIA52M7NSTKUAHKYH7F"
echo "   c. Click 'Actions' → 'Deactivate' (immediately)"
echo "   d. Click 'Actions' → 'Delete'"
echo "   e. Click 'Create access key'"
echo "   f. Copy new Access Key ID and Secret Access Key"
echo "   g. Update your .env file with new keys"
echo ""

echo "2️⃣  CHANGE DATABASE PASSWORD"
echo "   -------------------------"
echo "   a. Go to: https://console.aws.amazon.com/rds/home?region=us-east-1"
echo "   b. Click on 'database-1'"
echo "   c. Click 'Modify'"
echo "   d. Scroll to 'Settings' → 'Master password'"
echo "   e. Enter new password (save it securely!)"
echo "   f. Click 'Continue' → 'Apply immediately' → 'Modify DB instance'"
echo "   g. Update your .env file with new password"
echo ""

echo "3️⃣  CHECK RDS SECURITY GROUP"
echo "   -------------------------"
echo "   a. Go to: https://console.aws.amazon.com/rds/home?region=us-east-1"
echo "   b. Click on 'database-1'"
echo "   c. Click on the VPC security group (under 'Connectivity & security')"
echo "   d. Click 'Edit inbound rules'"
echo "   e. Add rule:"
echo "      - Type: PostgreSQL"
echo "      - Port: 5432"
echo "      - Source: My IP (or 0.0.0.0/0 for testing - NOT recommended for production)"
echo "   f. Click 'Save rules'"
echo ""

echo "4️⃣  VERIFY .ENV IS NOT IN GIT"
echo "   ---------------------------"
echo "   Running check..."
git ls-files .env 2>/dev/null
if [ $? -eq 0 ]; then
    echo "   ❌ ERROR: .env is tracked by git!"
    echo "   Run: git rm --cached .env"
    echo "   Run: git commit -m 'Remove .env from git'"
else
    echo "   ✅ GOOD: .env is not tracked by git"
fi
echo ""

echo "5️⃣  UPDATE YOUR .ENV FILE"
echo "   ----------------------"
echo "   After rotating keys and password, update .env:"
echo ""
echo "   # AWS Bedrock Configuration"
echo "   AWS_REGION=us-east-1"
echo "   AWS_ACCESS_KEY_ID=<NEW_KEY_HERE>"
echo "   AWS_SECRET_ACCESS_KEY=<NEW_SECRET_HERE>"
echo "   BEDROCK_MODEL_ID=amazon.nova-lite-v1:0"
echo ""
echo "   # PostgreSQL Configuration"
echo "   POSTGRES_HOST=database-1.cgp62acck1rv.us-east-1.rds.amazonaws.com"
echo "   POSTGRES_PORT=5432"
echo "   POSTGRES_DB=car_valuation"
echo "   POSTGRES_USER=postgres"
echo "   POSTGRES_PASSWORD=<NEW_PASSWORD_HERE>"
echo ""

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║              ⚠️  DO THESE STEPS IMMEDIATELY!                         ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Priority order:"
echo "1. Deactivate/Delete exposed AWS key (MOST URGENT)"
echo "2. Change database password"
echo "3. Update .env with new credentials"
echo "4. Configure RDS security group"
echo ""
